# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bbf0ccaf3d089c4a93b6341498f91e0151d90560ce7eceb0b971868ea277d7a5fe3dbcb6c55ff49a0ee56b3c0640cdad2a03f71b67e887e4c9a66085edf695c3

test:
  secret_key_base: 7a3df8ce8c10bfadcb504ac62857e8430f36f7699134ab68e46e3fb104fcafa16c9c0610eae4815e54c2726718c8b000b65a92f65de47ee00617b430e270bcc9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
